fix crash in paper when removing entities
kaboomserver/extras pull request #310
Opened 2022-04-20 14:50 UTC by ayunami2000

https://github.com/PaperMC/Paper/issues/6451

after testing for 5mins this did in fact seem to fix it

this breaks, for instance, custom maps that come with entities in them that extras then tries to remove. i had my server crashing every like 1-3 minutes after each startup due to this.

2022-04-20 14:54 UTC, allinkdev requested changes
Instead of using getInstance(), please use JavaPlugin.getPlugin(Main.class) as the rest of the plugin does.

2022-04-20 15:01 UTC, ayunami2000 commented
also note i do not know what this may do to the actual removing of entities, e.g. does it allow the entity to exist for any amount of time and if so is this a problem?

2022-04-20 15:09 UTC, allinkdev requested changes

2022-04-21 17:37 UTC, ayunami2000 commented
Hey, sorry for the delay! I'm super caught up with schoolwork rn, so if someone else wants to test that out for me it would help speed things along!

2022-05-20 04:19 UTC, closed without merging